version: '3.5'

services:
  postgres:
    container_name: cloudfox_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: cloudfox_mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-root}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME:-api_iv}
      MONGO_INITDB_USERNAME: ${MONGODB_USERNAME:-mongo}
      MONGO_INITDB_PASSWORD: ${MONGODB_PASSWORD:-mongo}
    ports:
      - 27017:27017

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
